let backgroundColor = "black";
let displayedMovies = 15;
let moviePages = 5;
let movie1Title = "Indiana Jones";
let movie2Title = "Shrek";
let movie3Title = "The Lion King";
let movie4Title = "World War Z";
let movie5Title = "SpongeBob";
let pageTitle = "Welcome to Netflix";
let autoplayMainMovie = false;
let maximumVideoFileSize = "5 GB";
let maximumVideoResoultion = "4K";
let maximumVideoFrames = 60;
let maximumAccountMembers = 5;
let userName = "Alexis";
let password = "1234";
let minimumResolution = 720
let sessionStatus = false;
let videoControls = true;
let timeToAskIfUserIsStillThereAfterMovieEnds = 60;

document.write("Welcome to Netflix. Some of the possible variables this site may have are: ");
document.write("<br>");
document.write("<br>");
document.write("backgroundColors: "+backgroundColor);
document.write("<br>");
document.write("displayedMovies: "+displayedMovies);
document.write("<br>");
document.write("moviePages: "+moviePages);
document.write("<br>");
document.write("movie1Title: "+movie1Title);
document.write("<br>");
document.write("movie2Title: "+movie2Title);
document.write("<br>");
document.write("movie3Title: "+movie3Title);
document.write("<br>");
document.write("movie4Title: "+movie4Title);
document.write("<br>");
document.write("movie5Title: "+movie5Title);
document.write("<br>");
document.write("pageTitle: "+pageTitle);
document.write("<br>");
document.write("autoplayMainMovie: "+autoplayMainMovie);
document.write("<br>");
document.write("maximumVideoFileSize: "+maximumVideoFileSize);
document.write("<br>");
document.write("maximumVideoResoultion: "+maximumVideoResoultion);
document.write("<br>");
document.write("maximumVideoFrames: "+maximumVideoFrames);
document.write("<br>");
document.write("maximumAccountMembers: "+maximumAccountMembers);
document.write("<br>");
document.write("userName: "+userName);
document.write("<br>");
document.write("password: "+password);
document.write("<br>");
document.write("minimumResolution: "+minimumResolution);
document.write("<br>");
document.write("sessionStatus: "+sessionStatus);
document.write("<br>");
document.write("videoControls: "+videoControls);
document.write("<br>");
document.write("timeToAskIfUserIsStillThereAfterMovieEnds: "+timeToAskIfUserIsStillThereAfterMovieEnds);
document.write("<br>");